Added CI cleanup to remove unused resources after CI execution

diff --git a/.github/workflows/daily-sanity-master.yml b/.github/workflows/daily-sanity-master.yml
--- a/.github/workflows/daily-sanity-master.yml
+++ b/.github/workflows/daily-sanity-master.yml
@@ -87,14 +87,14 @@ jobs:
         if [[ -z `curl -sS -u admin:admin http://$url:8080/SEMP -d "<rpc><show><config-sync></config-sync></show></rpc>" | grep "<oper-status>Up</oper-status>"` ]] ; then echo "config-sync not up!"; exit 1; fi
         pubSubTools/sdkperf_c -cip=$url -mn=100000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"
 
-#    - name: Delete test deployment (Cleanup)
-#      if: ${{ always() }}
-#      run: |
-#        aws cloudformation delete-stack --stack-name $TESTSTACKNAME || echo "Couldn't delete stack $TESTSTACKNAME"
-#        echo "Waiting for stack delete complete"
-#        stackid="$(aws cloudformation describe-stacks --stack-name $TESTSTACKNAME | grep StackId | awk -F '"' '{print $4}')"
-#        if [ -n "$stackid" ]; then until aws cloudformation describe-stacks --stack-name $stackid | grep -m 1 "DELETE_COMPLETE"; do sleep 10; done; fi
-#
+    - name: Delete test deployment (Cleanup)
+      if: ${{ always() }}
+      run: |
+        aws cloudformation delete-stack --stack-name $TESTSTACKNAME || echo "Couldn't delete stack $TESTSTACKNAME"
+        echo "Waiting for stack delete complete"
+        stackid="$(aws cloudformation describe-stacks --stack-name $TESTSTACKNAME | grep StackId | awk -F '"' '{print $4}')"
+        if [ -n "$stackid" ]; then until aws cloudformation describe-stacks --stack-name $stackid | grep -m 1 "DELETE_COMPLETE"; do sleep 10; done; fi
+
 #    - name: Testing with No Private Subnet
 #      run: |
 #        export TESTSTACKNAME2="$TESTSTACKNAME-1"
